# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trade.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '分类列表',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=128, verbose_name='物品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
                ('status', models.CharField(choices=[('R', 'Recommended'), ('A', 'Approved'), ('V', 'V')], default='R', max_length=1, verbose_name='状态')),
                ('kw', models.CharField(max_length=225, verbose_name='关键词')),
                ('description', models.TextField(verbose_name='描述')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('image', models.ImageField(height_field='height_field', upload_to=trade.models.upload_location, verbose_name='上传图片', width_field='width_field')),
                ('height_field', models.IntegerField(default=334, verbose_name='高度')),
                ('width_field', models.IntegerField(default=254, verbose_name='宽度')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Category')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': '物品',
                'verbose_name_plural': '物品列表',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='昵称')),
                ('wei', models.CharField(blank=True, max_length=40, verbose_name='微信')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('location', models.CharField(blank=True, max_length=40, verbose_name='住址')),
                ('grade', models.CharField(blank=True, choices=[('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四'), ('其他', '其他')], default='大四', max_length=40, verbose_name='年级')),
                ('college', models.CharField(blank=True, max_length=40, verbose_name='学院')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'ordering': ('-user__last_login',),
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='Seek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('招领', '招领'), ('求购', '求购')], default='求购', max_length=40, verbose_name='状态')),
                ('name', models.CharField(max_length=225, verbose_name='名称')),
                ('kw', models.CharField(max_length=225, verbose_name='关键词')),
                ('description', models.TextField(verbose_name='描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': '需求',
                'verbose_name_plural': '需求列表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='标签名')),
                ('description', models.CharField(max_length=1000, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(to='trade.Tag'),
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
